apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: rhacm-policies
  namespace: default
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - rhacm-policies
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-lpanza-ocp4-acm-acs-aap-day1-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-lpanza-ocp4-acm-acs-aap-day1
  namespace: ggithubcom-lpanza-ocp4-acm-acs-aap-day1-ns
spec:
  type: Git
  pathname: 'https://github.com/lpanza/ocp4-acm-acs-aap-day1'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: rhacm/policies
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: rhacm-policies
  name: rhacm-policies-subscription-1
  namespace: default
spec:
  channel: ggithubcom-lpanza-ocp4-acm-acs-aap-day1-ns/ggithubcom-lpanza-ocp4-acm-acs-aap-day1
  placement:
    placementRef:
      kind: Placement
      name: rhacm-policies-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: rhacm-policies
  name: rhacm-policies-placement-1
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'local-cluster'
              operator: 'In'
              values: 
              - true
  clusterSets:
    - default
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: default
  name: default
spec:
  clusterSet: default

